# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the RTL8370MB Switch device drivers.
#

obj-$(CONFIG_NET_DSA_REALTEK_RTL8370MB) += rtl8370_api.o

ccflags-y += -I$(srctree)/$(src) -I$(srctree)/$(src)/dal/rtl8367c

rtl8370_api-objs := acl.o \
		chip.o \
		cpu.o \
		dot1x.o \
		eee.o \
		gpio.o \
		i2c.o \
		igmp.o \
		interrupt.o \
		l2.o \
		leaky.o \
		led.o \
		mirror.o \
		oam.o \
		port.o \
		ptp.o \
		qos.o \
		rate.o \
		rldp.o \
		rtk_switch.o \
		stat.o \
		storm.o \
		svlan.o \
		trap.o \
		trunk.o \
		vlan.o \
		dal/dal_mgmt.o \
		dal/rtl8367c/dal_rtl8367c_acl.o \
		dal/rtl8367c/dal_rtl8367c_cpu.o \
		dal/rtl8367c/dal_rtl8367c_dot1x.o \
		dal/rtl8367c/dal_rtl8367c_eee.o \
		dal/rtl8367c/dal_rtl8367c_gpio.o \
		dal/rtl8367c/dal_rtl8367c_i2c.o \
		dal/rtl8367c/dal_rtl8367c_igmp.o \
		dal/rtl8367c/dal_rtl8367c_interrupt.o \
		dal/rtl8367c/dal_rtl8367c_l2.o \
		dal/rtl8367c/dal_rtl8367c_leaky.o \
		dal/rtl8367c/dal_rtl8367c_led.o \
		dal/rtl8367c/dal_rtl8367c_mapper.o \
		dal/rtl8367c/dal_rtl8367c_mirror.o \
		dal/rtl8367c/dal_rtl8367c_oam.o \
		dal/rtl8367c/dal_rtl8367c_port.o \
		dal/rtl8367c/dal_rtl8367c_ptp.o \
		dal/rtl8367c/dal_rtl8367c_qos.o \
		dal/rtl8367c/dal_rtl8367c_rate.o \
		dal/rtl8367c/dal_rtl8367c_rldp.o \
		dal/rtl8367c/dal_rtl8367c_stat.o \
		dal/rtl8367c/dal_rtl8367c_storm.o \
		dal/rtl8367c/dal_rtl8367c_svlan.o \
		dal/rtl8367c/dal_rtl8367c_switch.o \
		dal/rtl8367c/dal_rtl8367c_trap.o \
		dal/rtl8367c/dal_rtl8367c_trunk.o \
		dal/rtl8367c/dal_rtl8367c_vlan.o \
		dal/rtl8367c/rtl8367c_asicdrv_acl.o \
		dal/rtl8367c/rtl8367c_asicdrv.o \
		dal/rtl8367c/rtl8367c_asicdrv_cputag.o \
		dal/rtl8367c/rtl8367c_asicdrv_dot1x.o \
		dal/rtl8367c/rtl8367c_asicdrv_eav.o \
		dal/rtl8367c/rtl8367c_asicdrv_eee.o \
		dal/rtl8367c/rtl8367c_asicdrv_fc.o \
		dal/rtl8367c/rtl8367c_asicdrv_green.o \
		dal/rtl8367c/rtl8367c_asicdrv_hsb.o \
		dal/rtl8367c/rtl8367c_asicdrv_i2c.o \
		dal/rtl8367c/rtl8367c_asicdrv_igmp.o \
		dal/rtl8367c/rtl8367c_asicdrv_inbwctrl.o \
		dal/rtl8367c/rtl8367c_asicdrv_interrupt.o \
		dal/rtl8367c/rtl8367c_asicdrv_led.o \
		dal/rtl8367c/rtl8367c_asicdrv_lut.o \
		dal/rtl8367c/rtl8367c_asicdrv_meter.o \
		dal/rtl8367c/rtl8367c_asicdrv_mib.o \
		dal/rtl8367c/rtl8367c_asicdrv_mirror.o \
		dal/rtl8367c/rtl8367c_asicdrv_misc.o \
		dal/rtl8367c/rtl8367c_asicdrv_oam.o \
		dal/rtl8367c/rtl8367c_asicdrv_phy.o \
		dal/rtl8367c/rtl8367c_asicdrv_port.o \
		dal/rtl8367c/rtl8367c_asicdrv_portIsolation.o \
		dal/rtl8367c/rtl8367c_asicdrv_qos.o \
		dal/rtl8367c/rtl8367c_asicdrv_rldp.o \
		dal/rtl8367c/rtl8367c_asicdrv_rma.o \
		dal/rtl8367c/rtl8367c_asicdrv_scheduling.o \
		dal/rtl8367c/rtl8367c_asicdrv_storm.o \
		dal/rtl8367c/rtl8367c_asicdrv_svlan.o \
		dal/rtl8367c/rtl8367c_asicdrv_trunking.o \
		dal/rtl8367c/rtl8367c_asicdrv_unknownMulticast.o \
		dal/rtl8367c/rtl8367c_asicdrv_vlan.o \
		#dal/rtl8367c/rtl8367c_smi.o \
# JimmyLiu

