# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the ChargePoint network device drivers.
#

obj-$(CONFIG_CHPT_ETH_SPI)                  := eth_spi_master.o
ccflags-$(CONFIG_CHPT_ETH_SPI_DEBUG)        += -DDEBUG
ccflags-$(CONFIG_CHPT_ETH_SPI_VERBOSE)      += -DVERBOSE_DEBUG
